cabal-version:      3.0
name:               app
version:            0.1.0.0
synopsis:           tauri2-miso frontend (Miso, GHC WASM backend)
license:            BSD-3-Clause
build-type:         Simple

flag interactive
  default:
    False
  manual:
    True

common warnings
  ghc-options:
    -Wall

common wasm-options
  if arch(wasm32)
    ghc-options:
      -no-hs-main -optl-mexec-model=reactor "-optl-Wl,--export=hs_start"
    cpp-options:
      -DWASM
    if flag(interactive)
      cpp-options:
        -DINTERACTIVE

library greet-core
  import:
    warnings
  exposed-modules:
    Greet
  hs-source-dirs:
    src
  build-depends:
    base < 5, text
  default-language:
    Haskell2010

executable app
  import:
    warnings, wasm-options
  main-is:
    Main.hs
  hs-source-dirs:
    app
  build-depends:
    base < 5, text, miso >= 1.9, app:greet-core
  default-language:
    Haskell2010

test-suite greet-spec
  import:
    warnings
  type:
    exitcode-stdio-1.0
  main-is:
    GreetSpec.hs
  hs-source-dirs:
    test
  build-depends:
    base < 5, text, hspec, app:greet-core
  default-language:
    Haskell2010
